name: Test simple-va

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  go:
    uses: ./.github/workflows/pipelines.yml
    with:
      run-tests:      true
      do-build:      true
      run-vulncheck:  true
      do-build-docker: true
      do-release:       ${{ startsWith(github.ref, 'refs/tags/') }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}