name: Test simple-va

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  go:
    uses: ./.github/workflows/pipelines.yml
    with:
      run-tests:      true
      do-check-api-version:      true
      run-vulncheck:  true
      do-build:       ${{ startsWith(github.ref, 'refs/tags/') }}
