name: Test simple-va

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"  
  pull_request:
    branches:
      - main

env:
  GO_VERSION: &go_version "1.23.6"  # Set the global Go version

jobs:
  test-endpoint:
    name:  endpoint tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Golang Tests
        run: go test -v

  vulncheck:
    name:  govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: *go_version
          go-package: './...'
  
  build:
    name: Build and Inject Version
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only build on version tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: *go_version

      - name: Get build metadata
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Build Binary with Version Injection
        run: |
          go build -ldflags "-X 'main.Version=${VERSION}' -X 'main.Commit=${COMMIT}' -X 'main.BuildTime=${BUILD_TIME}'" -o simple-va ./cmd/main.go

      - name: Upload Built Binary
        uses: actions/upload-artifact@v4
        with:
          name: simple-va
          path: ./simple-va
