name: Test simple-va

on:
  push:
    branches:
      - main

jobs:
  test-endpoint:
    name:  endpoint tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Golang Tests
        run: go test -v

  vulncheck:
    name:  govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.23.6'
          go-package: './...'
