name: Vulnerability Check Only

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  vulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.24.2'
          go-package: './...'
